[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["panic_abort", "core"]
build-std-features = ["panic_immediate_abort"]
